
//----------------------------------------------------
// The following code was generated by Java(tm) CUP v0.9d
// Wed Oct 20 18:23:57 EDT 2004
//----------------------------------------------------

package jasmin;

/** JavaCup generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int SEP = 36;
  static final int TABLESWITCH = 33;
  static final int DTHROWS = 12;
  static final int DCATCH = 2;
  static final int USING = 17;
  static final int PRIVATE = 25;
  static final int DSOURCE = 11;
  static final int INTERFACE = 23;
  static final int STATIC = 28;
  static final int LOOKUPSWITCH = 32;
  static final int IS = 18;
  static final int DINTERFACE = 15;
  static final int Str = 38;
  static final int DFIELD = 5;
  static final int Int = 41;
  static final int DCLASS = 3;
  static final int ABSTRACT = 21;
  static final int EOF = 0;
  static final int METHOD = 20;
  static final int error = 1;
  static final int TRANSIENT = 30;
  static final int Insn = 40;
  static final int Word = 39;
  static final int DSUPER = 10;
  static final int DLIMIT = 6;
  static final int EQ = 35;
  static final int Num = 42;
  static final int DIMPLEMENTS = 14;
  static final int FROM = 19;
  static final int DMETHOD = 8;
  static final int COLON = 37;
  static final int NATIVE = 24;
  static final int PROTECTED = 26;
  static final int TO = 16;
  static final int DEND = 4;
  static final int FINAL = 22;
  static final int DEFAULT = 34;
  static final int PUBLIC = 27;
  static final int VOLATILE = 31;
  static final int DVAR = 13;
  static final int SYNCHRONIZED = 29;
  static final int DSET = 9;
  static final int DLINE = 7;
};

