
//----------------------------------------------------
// The following code was generated by Java(tm) CUP v0.9d
// Fri Dec 02 14:52:27 CET 2005
//----------------------------------------------------

package jasmin;

/** JavaCup generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int ANNOTATION = 41;
  static final int SEP = 49;
  static final int TABLESWITCH = 46;
  static final int DTHROWS = 12;
  static final int DCATCH = 2;
  static final int USING = 22;
  static final int PRIVATE = 34;
  static final int DSOURCE = 11;
  static final int INTERFACE = 32;
  static final int DBYTECODE = 16;
  static final int STATIC = 37;
  static final int LOOKUPSWITCH = 45;
  static final int IS = 23;
  static final int DINTERFACE = 15;
  static final int Str = 51;
  static final int OFFSET = 28;
  static final int DFIELD = 5;
  static final int Int = 54;
  static final int DCLASS = 3;
  static final int VARARGS = 44;
  static final int ABSTRACT = 30;
  static final int EOF = 0;
  static final int METHOD = 25;
  static final int TRANSIENT = 39;
  static final int error = 1;
  static final int Insn = 53;
  static final int STACK = 27;
  static final int Word = 52;
  static final int DSUPER = 10;
  static final int DLIMIT = 6;
  static final int EQ = 48;
  static final int Signed = 56;
  static final int Num = 55;
  static final int DIMPLEMENTS = 14;
  static final int FROM = 24;
  static final int DDEBUG = 17;
  static final int DSTACK = 20;
  static final int DMETHOD = 8;
  static final int COLON = 50;
  static final int NATIVE = 33;
  static final int PROTECTED = 35;
  static final int ENUM = 42;
  static final int TO = 21;
  static final int DEND = 4;
  static final int FINAL = 31;
  static final int DEFAULT = 47;
  static final int BRIDGE = 43;
  static final int PUBLIC = 36;
  static final int DENCLOSING = 18;
  static final int VOLATILE = 40;
  static final int SIGNATURE = 26;
  static final int DVAR = 13;
  static final int SYNCHRONIZED = 38;
  static final int DSET = 9;
  static final int LOCALS = 29;
  static final int DLINE = 7;
  static final int DSIGNATURE = 19;
};

